# Generated by Django 3.0.5 on 2020-04-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'meta_info',
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
            ],
            options={
                'db_table': 'opinions',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
                ('price', models.IntegerField(default=None, verbose_name='Бағасы')),
                ('image', models.URLField(verbose_name='Суреті')),
                ('position', models.IntegerField(verbose_name='Нешінші орналасады?')),
                ('is_highlight', models.BooleanField(default=False, verbose_name='Ерекшелеу')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
