# Generated by Django 3.0.5 on 2020-04-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='product',
            name='instagram_account',
            field=models.URLField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
