# Generated by Django 3.0.5 on 2020-04-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_customer_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaInfo',
        ),
    ]
