# Generated by Django 3.0.5 on 2020-04-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200430_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product_price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
