# Generated by Django 3.0.5 on 2020-04-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_customer_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
