# Generated by Django 3.0.5 on 2020-07-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200430_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Клинттер'},
        ),
        migrations.AlterModelOptions(
            name='opinion',
            options={'verbose_name_plural': 'Пікірлер'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['position'], 'verbose_name_plural': 'Тауарлар'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='instagram_account',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_highlight',
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/images', verbose_name='Суреті'),
        ),
    ]
